[libdefaults]
    default_realm = EXAMPLE.TEST
    dns_lookup_kdc = false
    dns_lookup_realm = false
    rdns = false
    udp_preference_limit = 1

[realms]
    EXAMPLE.TEST = {
        kdc = kdc.krb.test:88
    }

[domain_realm]
    .krb.test = EXAMPLE.TEST
    krb.test = EXAMPLE.TEST
